export const PARTS_LIST_REQUESTED = "PARTS_LIST_REQUESTED"
export const PARTS_LIST_REQUEST_SUCCESS = "PARTS_LIST_REQUEST_SUCCESS"
export const PARTS_LIST_REQUEST_ERROR = "PARTS_LIST_REQUEST_ERROR"

export const PARTS_EXCLUSIONS_REQUESTED = "PARTS_EXCLUSIONS_REQUESTED"
export const PARTS_EXCLUSIONS_REQUEST_SUCCESS = "PARTS_EXCLUSIONS_REQUEST_SUCCESS"
export const PARTS_EXCLUSIONS_REQUEST_ERROR = "PARTS_EXCLUSIONS_REQUEST_ERROR"